#!/bin/bash
# params:
# URMDB_USER
# URMDB_PWD
# URMDB_DBHOST
# URMDB_DBNAME

P_SQLFILE=$1
P_LOGFILE=$2

export PGPASSWORD="$URMDB_PWD"
psql -A -q -t -d $URMDB_DBNAME -h $URMDB_DBHOST -U $URMDB_USER < $P_SQLFILE > $P_LOGFILE 2>&1
