package org.urm.engine.meta;

import org.urm.common.RunError;

public class _Error {

	public static int ErrorBase = RunError.BaseEngineMeta;
	
	public static final int InvalidOSType1 = ErrorBase + 1;
	public static final int MissingOSType0 = ErrorBase + 2;
	public static final int InvalidCategory1 = ErrorBase + 3;
	public static final int MissingCategory0 = ErrorBase + 4;
	public static final int InvalidServerType1 = ErrorBase + 5;
	public static final int InvalidNodeType1 = ErrorBase + 6;
	public static final int MissingNodeType0 = ErrorBase + 7;
	public static final int InvalidDeployType1 = ErrorBase + 8;
	public static final int MissingDeployType0 = ErrorBase + 9;
	public static final int InvalidSourceItemType1 = ErrorBase + 10;
	public static final int MissingSourceItemType0 = ErrorBase + 11;
	public static final int InvalidDistributiveItemType1 = ErrorBase + 12;
	public static final int MissingDistributiveItemType0 = ErrorBase + 13;
	public static final int InvalidDistributiveItemSource1 = ErrorBase + 14;
	public static final int MissingDistributiveItemSource0 = ErrorBase + 15;
	public static final int InvalidBuildMode1 = ErrorBase + 16;
	public static final int InvalidDbmsType1 = ErrorBase + 17;
	public static final int MissingDbmsType0 = ErrorBase + 18;
	public static final int InvalidConfItemType1 = ErrorBase + 19;
	public static final int MissingConfItemType0 = ErrorBase + 20;
	public static final int InvalidItemVersionType1 = ErrorBase + 21;
	public static final int WrongNameAttribute1 = ErrorBase + 22;
	public static final int InvalidBaseSrcType1 = ErrorBase + 23;
	public static final int MissingBaseSrcType0 = ErrorBase + 24;
	public static final int InvalidBaseSrcFormat1 = ErrorBase + 25;
	public static final int DuplicateOSType1 = ErrorBase + 26;
	public static final int UnknownSystemFilesCharset1 = ErrorBase + 27;
	public static final int UnknownSchema1 = ErrorBase + 28;
	public static final int UnknownDatagroup1 = ErrorBase + 29;
	public static final int InvalidDesignElementType1 = ErrorBase + 30;
	public static final int MissingDesignElementType0 = ErrorBase + 31;
	public static final int InvalidDesignLinkType1 = ErrorBase + 32;
	public static final int MissingDesignLinkType0 = ErrorBase + 33;
	public static final int UnknownDesignElement1 = ErrorBase + 34;
	public static final int NestedGroupsDisallowed1 = ErrorBase + 35;
	public static final int NonGroupItemChilds1 = ErrorBase + 36;
	public static final int UnknownDesignLink1 = ErrorBase + 37;
	public static final int UnableGetGroupItem0 = ErrorBase + 38;
	public static final int UnknownDistributiveComponent1 = ErrorBase + 39;
	public static final int UnknownDistributiveItem1 = ErrorBase + 40;
	public static final int UnknownConfigurationItem1 = ErrorBase + 41;
	public static final int UnknownDelivery1 = ErrorBase + 42;
	public static final int UnknownDistributiveItemType2 = ErrorBase + 43;
	public static final int UnableGetFileVersionType2 = ErrorBase + 44;
	public static final int ArchiveTypeNotSupported1 = ErrorBase + 45;
	public static final int InvalidConfItemDef1 = ErrorBase + 46;
	public static final int UnknownDeliveryBinaryItem1 = ErrorBase + 47;
	public static final int UnknownDeliveryConfigurationItem1 = ErrorBase + 48;
	public static final int UnknownDeliverySchema1 = ErrorBase + 49;
	public static final int UnknownDeliveryDatagroup1 = ErrorBase + 50;
	public static final int UnknownDatacenter1 = ErrorBase + 51;
	public static final int NoDatacenterDefined0 = ErrorBase + 52;
	public static final int UnknownServer1 = ErrorBase + 53;
	public static final int RootpathEmptyRequiredForDeployments1 = ErrorBase + 54;
	public static final int RootpathEmptyRequiredForGeneric1 = ErrorBase + 55;
	public static final int InvalidServerNode2 = ErrorBase + 56;
	public static final int MissingServerPrimaryNode1 = ErrorBase + 57;
	public static final int MissingStandbyNode0 = ErrorBase + 58;
	public static final int MissingActiveNode0 = ErrorBase + 59;
	public static final int UnexpectedDeploymentType1 = ErrorBase + 60;
	public static final int UnknownDeploymentPath0 = ErrorBase + 61;
	public static final int MissingProxyNode0 = ErrorBase + 62;
	public static final int UnknownDatabaseFilesCharset1 = ErrorBase + 63;
	public static final int UnableGetBuildModeSettings1 = ErrorBase + 64;
	public static final int InconsistentVersionAttributes0 = ErrorBase + 65;
	public static final int UnknownSourceSet1 = ErrorBase + 66;
	public static final int UnknownSourceProject1 = ErrorBase + 67;
	public static final int UnknownSourceProjectItem2 = ErrorBase + 68;
	public static final int UnknownJavaVersion0 = ErrorBase + 69;
	public static final int UnknownMavenVersion0 = ErrorBase + 70;
	public static final int UnknownBuilderVersion1 = ErrorBase + 71;
	public static final int UnknownProjectCategory1 = ErrorBase + 72;

}
